LANGUAGES = {
    'en': {
        'title': "IoT Client for Elevator Monitoring",
        'server_url': "Server URL:",
        'elevator_id': "Elevator ID:",
        'start_simulation': "Start Simulation",
        'stop_simulation': "Stop Simulation",
        'control_panel': "Control Panel:",
        'toggle_power': "Toggle Power",
        'toggle_stuck': "Toggle Stuck",
        'toggle_move': "Toggle Move",
        'simulation_started': "Starting simulation...",
        'simulation_stopped': "Simulation stopped.",
        'power_toggled': "Power toggled to {state}.",
        'stuck_toggled': "Stuck state toggled: Elevator is {state}.",
        'movement_toggled': "Movement state toggled: Elevator is {state}.",
        'invalid_elevator_id': "Error: Invalid Elevator ID. Please enter a number.",
        'state_on': "ON",
        'state_off': "OFF",
        'state_stuck': "stuck",
        'state_moving_normally': "moving normally",
        'state_moving': "moving",
        'state_stopped': "stopped",
        'invalid_elevator_id': "Error: Invalid Elevator ID. Please enter a number.",
        'sent': "Sent",
        'response': "Response",
        'settings': "Settings",
        'date_format': "Date Format",
        'time_zone': "Time Zone",
        'unit_system': "Unit system",
        'save_settings': "Save settings",
        'temperature_min': "Temperature Min",
        'temperature_max': "Temperature Max",
        'humidity_min': "Humidity Min",
        'humidity_max': "Humidity Max",
        'weight': "Weight",
        'apply_simulation_params': "Apply Params"
    },
    'uk': {
        'title': "IoT Клієнт для Моніторингу Ліфтів",
        'server_url': "URL сервера:",
        'elevator_id': "ID ліфта:",
        'start_simulation': "Запустити симуляцію",
        'stop_simulation': "Зупинити симуляцію",
        'control_panel': "Панель керування:",
        'toggle_power': "Перемкнути живлення",
        'toggle_stuck': "Перемкнути застрягання",
        'toggle_move': "Перемкнути рух",
        'simulation_started': "Запуск симуляції...",
        'simulation_stopped': "Симуляція зупинена.",
        'power_toggled': "Живлення перемкнуто на {state}.",
        'stuck_toggled': "Стан застрягання перемкнуто: Ліфт {state}.",
        'movement_toggled': "Стан руху перемкнуто: Ліфт {state}.",
        'invalid_elevator_id': "Помилка: Невірний ID ліфта. Введіть число.",
        'state_on': "УВІМКНЕНО",
        'state_off': "ВИМКНЕНО",
        'state_stuck': "застряг",
        'state_moving_normally': "рухається нормально",
        'state_moving': "рухається",
        'state_stopped': "зупинений",
        'invalid_elevator_id':"Помилка: Невірний ідентифікатор ліфта. Будь ласка, введіть число.",
        'sent': "Надіслано",
        'response': "Отримано відповідь",
        'settings': "Налаштування",
        'date_format': "Формат дати",
        'time_zone': "Часовий пояс",
        'unit_system': "Система одиниць",
        'save_settings': "Зберегти налаштування",
        'temperature_min': "Мін. температура",
        'temperature_max': "Макс. температура",
        'humidity_min': "Мін. вологість",
        'humidity_max': "Макс. вологість",
        'weight': "Вага",
        'apply_simulation_params': "Надіслати параметри"
    }
}